export { default as Home } from './Home';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Dashboard } from './Dashboard';
export { default as NavBar } from './NavBar';
export { default as SearchBar } from './SearchBar';
export { default as VerifyUser } from './VerifyUser';
export { default as AddBank } from './AddBank';
export { default as Pay } from './Pay';